### ISSUE TITLE
Logica met datums werkt niet

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1652]
### Product versie / Product version

1.1.0

### Omschrijf het probleem / Describe the bug

```
Traceback (most recent call last):
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/drf_spectacular/drainage.py", line 135, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/joeri/projects/open-formulieren/open-forms/src/openforms/submissions/api/serializers.py", line 262, in to_representation
    new_configuration = evaluate_form_logic(
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/elasticapm/traces.py", line 871, in decorated
    return func(*args, **kwds)
  File "/home/joeri/projects/open-formulieren/open-forms/src/openforms/submissions/form_logic.py", line 92, in evaluate_form_logic
    if jsonLogic(rule.json_logic_trigger, data):
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/json_logic/__init__.py", line 224, in jsonLogic
    values = [jsonLogic(val, data) for val in values]
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/json_logic/__init__.py", line 224, in <listcomp>
    values = [jsonLogic(val, data) for val in values]
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/json_logic/__init__.py", line 242, in jsonLogic
    return operations[operator](*values)
  File "/home/joeri/projects/open-formulieren/open-forms/env/lib/python3.8/site-packages/json_logic/__init__.py", line 123, in get_date
    return date.fromisoformat(date_str)
ValueError: Invalid isoformat string: ''
```

### Stappen om te reproduceren / Steps to reproduce

See: https://open-forms.readthedocs.io/en/latest/manual/forms/examples/logic_rules.html

**Comment by Bartvaderkin** [comment]
This fails because there is no except clause here: https://github.com/maykinmedia/json-logic-py/blob/1ceb93ad165d69a5639edc623d5613d0229c05e2/json_logic/__init__.py#L126

We could add it but I'm not 100% sure what to do when this fails. Just return null or raise something?

**Comment by SilviaAmAm** [comment]
Apparently this happens when downloading and importing the form file from the documentation.
Creating a new form does not give this error

**Comment by joeribekker** [comment]
Nice catch

**Comment by SilviaAmAm** [comment]
The comment was to remind myself what you said about reproducing the error (so that I wouldn't forget).

But I still can't reproduce this error.

I checked out both 1.1.0 for OF and the SDK.

**Comment by SilviaAmAm** [comment]
I tried using the file `docs/manual/forms/examples/_assets/logic_age.zip` from the 1.1.0 version. This file still had an old version of the trigger, and if I try to import this form in the `1.1.0`, I get the error:
```
Er is iets foutgegaan bij het importeren van formulier: {'json_logic_trigger': [ErrorDetail(string='Ongeldige JSON-logic', code='invalid')]}
```
The new version of the form/creating the form from scratch doesn't cause this error.

So it is possible that you had this old form already imported?

**Comment by joeribekker** [comment]
It was my local dev environment which included an older version of json-logic which took precedence over maykin-json-logic.

I can confirm the issue is resolved when the old lib is removed.
