### ISSUE TITLE
Migration `config.0029_rename_design_tokens` fails for empty `GlobalConfiguration.design_token_values`

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#1664]
### Product versie / Product version

1.1.0

### Omschrijf het probleem / Describe the bug

Running the migration `config.0029_rename_design_tokens` fails if `GlobalConfiguration.design_token_values` is an empty dict because of the following error:

```
+ echo Apply database migrations
Apply database migrations
+ python src/manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, admin_index, appointments, auth, authtoken, axes, bag, brp, config, contenttypes, cookie_consent, cspreports, custom_field_types, digid_eherkenning_oidc_generics, django_camunda, django_yubin, emails, forms, jcc, kvk, logging, microsoft, mozilla_django_oidc_db, multidomain, otp_static, otp_totp, payments, payments_ogone, prefill, prefill_haalcentraal, products, qmatic, registrations_email, registrations_microsoft_graph, registrations_objects_api, sessions, stuf, stuf_bg, stuf_zds, submissions, timeline_logger, two_factor, zgw_apis, zgw_consumers
Running migrations:
/app/src/openforms/prefill/contrib/stufbg/plugin.py:7: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
  from defusedxml.lxml import fromstring as df_fromstring
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/dbapi2.py", line 210, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/dbapi2.py", line 245, in _trace_sql
    result = method(sql, params)
psycopg2.errors.NotNullViolation: null value in column "design_token_values" violates not-null constraint
DETAIL:  Failing row contains (1, {}, , f, , <p>Bedankt voor het insturen van het formulier.</p>, f, Begin formulier, Wijzig, Bevestig, Vorige pagina, Volgende, Vorige pagina, Sla formulier op, , , null, , null, , , null, 60, 15, null, , , 90, 30, delete_permanently, 7, delete_permanently, 7, delete_permanently, f, t, <p>Ja, ik heb kennis genomen van het {% privacy_policy %} en gee..., https://en.wikipedia.org/wiki/Privacy_policy, {year}, <p>Dear Sir, Madam,<br /><br />You have submitted the form "{{ f..., Confirmation of your {{ form_name }} submission, {}, t, f, 5, f, , ).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/src/openforms/config/migrations/0029_rename_design_tokens.py", line 75, in operation
    config.save(update_fields=["design_token_values"])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/dbapi2.py", line 210, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/usr/local/lib/python3.8/site-packages/elasticapm/instrumentation/packages/dbapi2.py", line 245, in _trace_sql
    result = method(sql, params)
django.db.utils.IntegrityError: null value in column "design_token_values" violates not-null constraint
DETAIL:  Failing row contains (1, {}, , f, , <p>Bedankt voor het insturen van het formulier.</p>, f, Begin formulier, Wijzig, Bevestig, Vorige pagina, Volgende, Vorige pagina, Sla formulier op, , , null, , null, , , null, 60, 15, null, , , 90, 30, delete_permanently, 7, delete_permanently, 7, delete_permanently, f, t, <p>Ja, ik heb kennis genomen van het {% privacy_policy %} en gee..., https://en.wikipedia.org/wiki/Privacy_policy, {year}, <p>Dear Sir, Madam,<br /><br />You have submitted the form "{{ f..., Confirmation of your {{ form_name }} submission, {}, t, f, 5, f, , ).
```

**Comment by stevenbal** [comment]
The test environment for Den Haag automatically updates every night, it seems that the latest update causes issues on migration?
