### ISSUE TITLE
`prefill_config_empty_or_complete` violation.

### ISSUE THREAD

**Issue by pyhrr0** [open-formulieren/open-forms#2262]
### Product versie / Product version

2.0.0

### Omschrijf het probleem / Describe the bug

When I try to upgrade from 1.1.7 to 2.0.0, the migrations fail.

```
+ export PGHOST=mydb
+ export PGPORT=5432
+ fixtures_dir=/app/fixtures
+ uwsgi_port=8000
+ uwsgi_processes=4
+ uwsgi_threads=1
+ pg_isready
mydb:5432 - accepting connections
+ echo Database is up.
Database is up.
+ echo Apply database migrations
Apply database migrations
+ python src/manage.py migrate
No forms with duplicate keys in the form definitions found.
No form definitions with invalid keys.
Geen formulieren met logica in de 'geavanceerd' tab die niet naar backend logica kunnen worden omgezet.
Operations to perform:
  Apply all migrations: accounts, admin, admin_index, analytics_tools, appointments, auth, authtoken, axes, bag, brp, config, contenttypes, cookie_consent, cspreports, custom_field_types, digid_eherkenning_oidc_generics, django_camunda, django_yubin, emails, forms, jcc, kvk, logging, microsoft, mozilla_django_oidc_db, multidomain, of_authentication, otp_static, otp_totp, payments, payments_ogone, prefill, prefill_haalcentraal, products, qmatic, registrations_email, registrations_microsoft_graph, registrations_objects_api, sessions, simple_certmanager, stuf, stuf_bg, stuf_zds, submissions, timeline_logger, two_factor, upgrades, zgw_apis, zgw_consumers
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.CheckViolation: new row for relation "forms_formvariable" violates check constraint "prefill_config_empty_or_complete"
DETAIL:  Failing row contains (16, Achternaam, achternaam, component, demo, , string, , t, "", 2, 12).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/src/openforms/forms/migrations/0033_formvariable_datamigration.py", line 21, in create_form_variables_for_form
    FormVariable.objects.create_for_form(form)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/app/src/openforms/forms/models/form_variable.py", line 49, in create_for_form
    self.create_for_formstep(form_step)
  File "/app/src/openforms/forms/models/form_variable.py", line 101, in create_for_formstep
    return self.bulk_create(form_variables)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1287, in _batched_insert
    inserted_rows.extend(self._insert(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: new row for relation "forms_formvariable" violates check constraint "prefill_config_empty_or_complete"
DETAIL:  Failing row contains (16, Achternaam, achternaam, component, demo, , string, , t, "", 2, 12).

  Applying forms.0033_formvariable_datamigration...
```

### Stappen om te reproduceren / Steps to reproduce

1. open-forms 1.1.7:

```
$ kubectl exec -it open-forms-7c56b6dd48-v5hvh -- /bin/bash
maykin@open-forms-7c56b6dd48-v5hvh:/app$ python src/manage.py check_duplicate_component_keys
No forms with duplicate keys in the form definitions found.
maykin@open-forms-7c56b6dd48-v5hvh:/app$ python src/manage.py check_invalid_field_keys
No form definitions with invalid keys.
```

2. Use the same DB with open-forms 2.0.0

### Verwacht gedrag / Expected behavior

I'd expect the migrations to run successfully.

**Tasks**

So, the problem is that the demo plugin is not always saved in combination with an attribute (see screenshot below in comments). This should be reproduced and fixed in the code.

* [x] Write a test to show the problem. You can use a factories to create relevant data and run the `FormVariable.objects.create_for_form(form)` or even more narrow `create_for_form_field` to show the problem.
* [x] Change the code to solve the problem (see code and comments below)

**Comment by sergei-maertens** [comment]
we'll add an additional check so this can be detected and corrected before upgrading is attempted

**Comment by joeribekker** [comment]
For reference only: I added a small workaround in the code to fix this runtime by setting the attribute to "random_number" if the plugin is "demo" and there is no attribute known.

`src/openforms/forms/models/form_variable.py:76`

```python
            prefill_attr = glom(
                        component,
                        Path("prefill", "attribute"),
                        default="",
                        skip_exc=KeyError,
                    )
            prefill_plug = glom(
                        component,
                        Path("prefill", "plugin"),
                        default="",
                        skip_exc=KeyError,
                    )

            # THIS RESOLVES THE ABOVE ISSUE BUT IS OFCOURSE VERY NAIVE
            if prefill_plug == "demo" and not prefill_attr:
                prefill_attr = "random_number"

            form_variables.append(
                self.model(
                    form=form_step.form,
                    form_definition=form_step.form_definition,
                    prefill_plugin=prefill_plug,
                    prefill_attribute=prefill_attr,
                    key=component["key"],
                    name=component.get("label") or component["key"],
                    is_sensitive_data=component.get("isSensitiveData", False),
                    source=FormVariableSources.component,
                    data_type=get_component_datatype(component),
                    initial_value=get_component_default_value(component),
                )
            )
```

**Comment by joeribekker** [comment]
I'm removing triage because this seems a more often occuring problem and the fix is relatively easy.

**Comment by joeribekker** [comment]
> hm, this highlights a possible problem with the demo plugin and storing that information in a variable 🤔 because the demo plugin doesn't use attributes at all

It does:

![image](https://user-images.githubusercontent.com/96970/200897026-51ca01fa-017e-4e0e-b6d7-702e62478f6a.png)
