### ISSUE TITLE
Look into test failures

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2622]
The `--parallel` mode of the tests is uncovering some more heisentests.

Known flaky tests:

**admin test**

```
ERROR: test_registry_list_for_defaults (openforms.prefill.tests.test_admin.PrefillConfigTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/runner/work/open-forms/open-forms/src/openforms/prefill/tests/test_admin.py", line 30, in test_registry_list_for_defaults
    self.assertGreater(len(response.form["default_company_plugin"].options), 1)
AttributeError: 'Text' object has no attribute 'options'
```

From Slack:

> actually, it sounds more to me like it's thread safety problems in dynamically altering the form field widget/type in `PrefillConfigAdmin`

**Excel file generation**

Very low occurrence, but some bytes are different sometimes, causing test failures?

**Unknown**

Some failures are unknown and eaten by the `--parallel` mode, for example here: https://github.com/open-formulieren/open-forms/actions/runs/4042602805/jobs/6950504659

```
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 347, in _run_subsuite
    result = runner.run(subsuite)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 294, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/testcases.py", line 245, in __call__
    self._setup_and_call(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/testcases.py", line 281, in _setup_and_call
    super().__call__(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 599, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 513, in _feedErrorsToResult
    result.addSubTest(test.test_case, test, exc_info)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 251, in addSubTest
    self.check_subtest_picklable(test, subtest)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 209, in check_subtest_picklable
    self._confirm_picklable(subtest)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 142, in _confirm_picklable
    pickle.loads(pickle.dumps(obj))
AttributeError: Can't pickle local object '_get_target.<locals>.<lambda>'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/core/management/commands/test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 729, in run_tests
    result = self.run_suite(suite)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 670, in run_suite
    return runner.run(suite)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/runner.py", line [184](https://github.com/open-formulieren/open-forms/actions/runs/4042602805/jobs/6950504659#step:12:185), in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 411, in run
    subsuite_index, events = test_results.next(timeout=0.1)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 347, in _run_subsuite
    result = runner.run(subsuite)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 294, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/testcases.py", line 245, in __call__
    self._setup_and_call(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/testcases.py", line 281, in _setup_and_call
    super().__call__(result)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 599, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/unittest/case.py", line 513, in _feedErrorsToResult
    result.addSubTest(test.test_case, test, exc_info)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 251, in addSubTest
    self.check_subtest_picklable(test, subtest)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line [209](https://github.com/open-formulieren/open-forms/actions/runs/4042602805/jobs/6950504659#step:12:210), in check_subtest_picklable
    self._confirm_picklable(subtest)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/django/test/runner.py", line 142, in _confirm_picklable
    pickle.loads(pickle.dumps(obj))
AttributeError: Can't pickle local object '_get_target.<locals>.<lambda>'
```

This seems to happen with `subTest` at times?

**Comment by SilviaAmAm** [comment]
More info for the pickling error:
```
Subtest failed:

    test: test_doc_creation_failure_does_not_create_more_doc_ids (openforms.registrations.contrib.stuf_zds.tests.test_failure_modes.PartialRegistrationFailureTests)
 subtest: test_doc_creation_failure_does_not_create_more_doc_ids (openforms.registrations.contrib.stuf_zds.tests.test_failure_modes.PartialRegistrationFailureTests) [Document id generation fails]

Unfortunately, the subtest that failed cannot be pickled, so the parallel
test runner cannot handle it cleanly. Here is the pickling error:

> Can't pickle local object '_get_target.<locals>.<lambda>'
```

**Comment by sergei-maertens** [comment]
Rare occurrence that the XLSX export failed locally:

```
FAIL: test_submission_with_email_backend_export_csv_xlsx (openforms.registrations.contrib.email.tests.test_backend.EmailBackendTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/registrations/contrib/email/tests/test_backend.py", line 454, in test_submission_with_email_backend_export_csv_xlsx
    self.assertEqual(xlsx_export[1], create_submission_export(qs).export("xlsx"))
AssertionError: b'PK\[29 chars]00\x98\x8c>V\x07AMb\x81\x00\x00\x00\xb1\x00\x0[14164 chars]\x00' != b'PK\[29 chars]00\x99\x8c>V\x07AMb\x81\x00\x00\x00\xb1\x00\x0[14164 chars]\x00'
```

**Comment by SilviaAmAm** [comment]
I tried adding this test under the failing excel test:
```python
    def test_heisenbug(self):
        data = {"foo": "bar", "some_list": ["value1", "value2"]}

        submission = SubmissionFactory.create(form=self.form)
        submission_step = SubmissionStepFactory.create(
            submission=submission, form_step=self.fs, data=data
        )
        submission.completed_on = timezone.make_aware(datetime(2021, 1, 1, 12, 0, 0))
        submission.save()

        SubmissionFileAttachmentFactory.create(
            submission_step=submission_step,
            file_name="my-foo.bin",
            content_type="application/foo",
        )
        SubmissionFileAttachmentFactory.create(
            submission_step=submission_step,
            file_name="my-bar.txt",
            content_type="text/bar",
        )

        exported_data = []
        for _ in range(100):
            exported_data.append(create_submission_export(
                Submission.objects.filter(pk=submission.pk).select_related(
                    "auth_info"
                )
            ).export(AttachmentFormat.xlsx))

        for index, item in enumerate(exported_data[1:]):
            with self.subTest(index):
                self.assertEqual(item, exported_data[0])
```
This fails about 50% of the time when run on its own. When it fails:
1. as soon as one subtest fails, all the next ones fail too (but they don't always start from the same index)
2. The bytes shown in the assertion errors are always different between each run. For example, from three different failed runs:
```
AssertionError: b'PK\[29 chars]00\x8fT?V\x07AMb\x81\x00\x00\x00\xb1\x00\x00\x[14053 chars]\x00' != b'PK\[29 chars]00\x8eT?V\x07AMb\x81\x00\x00\x00\xb1\x00\x00\x[14053 chars]\x00'

AssertionError: b'PK\[29 chars]00\xc9T?V\x07AMb\x81\x00\x00\x00\xb1\x00\x00\x[14018 chars]\x00' != b'PK\[29 chars]00\xc8T?V\x07AMb\x81\x00\x00\x00\xb1\x00\x00\x[14018 chars]\x00'

AssertionError: b'PK\[29 chars]00\x02U?V\x07AMb\x81\x00\x00\x00\xb1\x00\x00\x[14080 chars]\x00' != b'PK\[29 chars]00\x01U?V\x07AMb\x81\x00\x00\x00\xb1\x00\x00\x[14080 chars]\x00'
```
