### ISSUE TITLE
Running selenium tests with Firefox driver doesn't work

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2640]
### Product versie / Product version

2.1.0-beta.0

### Omschrijf het probleem / Describe the bug

When running the selenium tests with Firefox webdriver, the following error happens: 

```
======================================================================
ERROR: test_editing_translatable_properties (openforms.forms.tests.selenium_tests.test_form_designer.FormDesignerComponentTranslationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/silvia/.pyenv/versions/3.10.4/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/silvia/.pyenv/versions/3.10.4/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/home/silvia/.pyenv/versions/3.10.4/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/test/utils.py", line 387, in inner
    return func(*args, **kwargs)
  File "/home/silvia/repositories/open-forms/src/openforms/forms/tests/selenium_tests/test_form_designer.py", line 106, in test_editing_translatable_properties
    scroll_into_view.perform()
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/selenium/webdriver/common/action_chains.py", line 78, in perform
    self.w3c_actions.perform()
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/selenium/webdriver/common/actions/action_builder.py", line 88, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (912, 740) is out of bounds of viewport width (1366) and height (683)
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5
MoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:370:5
assertInViewPort@chrome://remote/content/marionette/action.sys.mjs:2113:11
dispatch@chrome://remote/content/marionette/action.sys.mjs:1149:21
dispatch/pendingEvents<@chrome://remote/content/marionette/action.sys.mjs:1827:14
dispatch@chrome://remote/content/marionette/action.sys.mjs:1826:39
dispatch/chainEvents<@chrome://remote/content/marionette/action.sys.mjs:1753:27
dispatch@chrome://remote/content/marionette/action.sys.mjs:1755:7
performActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:472:23
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:139:31
```

This seems to have to do with the fact that while other webdrivers treat `move_to_element` as a scroll + hover action, while Firefox expects an explicit scroll action. (See [here](https://stackoverflow.com/a/52045231/7146757) and [here](https://github.com/mozilla/geckodriver/issues/776) for more details)

**Comment by SilviaAmAm** [comment]
Closing since we now use playwright
