### ISSUE TITLE
KeyError: 'form_steps': cannot import form

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2669]
### Product versie / Product version

2.0.1-denhaag

### Omschrijf het probleem / Describe the bug

Importing a form that contains a logic rule with action "mark step as not applicable" gives the following error:
```
2023-02-08 17:13:51,145 ERROR django.request  Internal Server Error: /admin/forms/form/import/
Traceback (most recent call last):
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 71, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 104, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/silvia/repositories/open-forms/src/openforms/forms/admin/views.py", line 85, in form_valid
    self._import_single_form(import_file)
  File "/home/silvia/repositories/open-forms/src/openforms/forms/admin/views.py", line 108, in _import_single_form
    created_fds = import_form(import_file)
  File "/home/silvia/.pyenv/versions/3.10.4/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/silvia/repositories/open-forms/src/openforms/forms/utils.py", line 137, in import_form
    return import_form_data(import_data, existing_form_instance)
  File "/home/silvia/.pyenv/versions/3.10.4/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/silvia/repositories/open-forms/src/openforms/forms/utils.py", line 225, in import_form_data
    deserialized.is_valid(raise_exception=True)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 483, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 618, in run_validation
    value = self.to_internal_value(data)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 666, in to_internal_value
    validated = self.child.run_validation(item)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 483, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/home/silvia/.pyenv/versions/open-forms/lib/python3.10/site-packages/rest_framework/fields.py", line 568, in run_validation
    value = self.to_internal_value(data)
  File "/home/silvia/repositories/open-forms/src/openforms/forms/api/serializers/logic/fields.py", line 28, in to_internal_value
    related_form_steps = self.parent.context["form_steps"]
KeyError: 'form_steps'
```

### Stappen om te reproduceren / Steps to reproduce

In the admin:
1. Create a form with 2 steps called "step1" and "step2", each with a text field "textfield1" and "textfield2" respectively
2. Add a logic rule which says if textfield1 is equal to "test" mark the step "step2" as not applicable.
3. Save the form
4. export the form

Now try to import the form. See the error.

I think that the problem is that this fix: https://github.com/open-formulieren/open-forms/commit/d43a9cdd2e723434ddb4c1f690b75f21cae82e23 has not been backported?

### Screen resolution

None

### Device

None

### OS

None

**Comment by SilviaAmAm** [comment]
Fixed by https://github.com/open-formulieren/open-forms/pull/2672
