### ISSUE TITLE
Crash on logic rule logging

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2893]
### Product versie / Product version

2.1.0 / latest

### Omschrijf het probleem / Describe the bug

Celery traceback:

```
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/logging/tasks.py", line 43, in log_logic_evaluation
    log_entry = _log_logic_evaluation(
  File "/home/bbt/code/open-forms/src/openforms/logging/logic.py", line 57, in log_logic_evaluation
    input_data += rule_introspection.get_input_components(
  File "/home/bbt/code/open-forms/src/openforms/utils/json_logic/datastructures.py", line 57, in get_input_components
    component_meta = components_map[key]
KeyError: 'today'
```

Logic rule:

![image](https://user-images.githubusercontent.com/5518550/225599527-448a3aa6-d870-48f0-9ba9-5e11d5ffdc53.png)

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Checked on 2.0.5 what the logic rule logging looks like now:

![image](https://user-images.githubusercontent.com/5518550/225661899-81e8760a-cbce-4850-ba48-4159304bcef3.png)

This is for the rule:

![image](https://user-images.githubusercontent.com/5518550/225662034-1beb928b-2034-4570-ba44-16027d0b5d9b.png)

It's not ideal, but does show that not just the resulting variable is relevant, but also the expression how we got there.

**Comment by joeribekker** [comment]
Refinement: Caused by missing test and issue arrived after refactor. Chris made a fix in a PR (?) but needs more.
Good news: This is all logged and functionality doesnt break but it could cause other exceptions to be missed.

User defined and static variables don't seem to work causing a crash. Although there is a bigger issue Joeri wants this patched without refactoring everything.
