### ISSUE TITLE
Something messes with logging causing test output to be cluttered

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3876]
e.g.

```
(open-forms) ➜  open-forms git:(chore/3049-upgrade-factory-boy) runtests src -k FormStepSubmissionTests                                                 
Using existing test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (upgrades.W001) Current code version was determined as 'dev', which prevents us from checking your upgrade path. Proceed at your own risk.
	HINT: We recommend only upgrading to tagged releases.

System check identified 1 issue (0 silenced).
.Exception e063de56-fa63-455a-accb-0d81daf7c337 ocurred
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authenticatiegegevens zijn niet opgegeven.
.Exception 7d359dc9-5db9-4d67-9ecc-c2923216acd4 ocurred
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/viewsets.py", line 529, in update
    instance, serializer = self._validate_step_input(request)
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/viewsets.py", line 591, in _validate_step_input
    instance = self.get_object()
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/viewsets.py", line 498, in get_object
    raise NotFound(_("Invalid form step reference given."))
rest_framework.exceptions.NotFound: Ongeldige formulierstapverwijzing.
.....
----------------------------------------------------------------------
Ran 7 tests in 0.685s

OK
Preserving test database for alias 'default'...
```

interestingly, I'm not seeing this happening to this extent in CI, so maybe I messed up my local config

**Comment by sergei-maertens** [comment]
resolved in my `local.py` with:

```py
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.UnsaltedMD5PasswordHasher"]

    DATABASES["default"]["PORT"] = 5433
    DATABASES["default"]["USER"] = "postgres"

    if "VERBOSE" not in os.environ:
        # shut up logging
        _LOGGING["loggers"].update(
            {
                "openforms.api.exception_handling": {
                    "handlers": ["console"],
                    "level": "CRITICAL",
                    "propagate": False,
                },
            }
        )

    LOG_REQUESTS = False
```
good enough
