### ISSUE TITLE
Solve PDF form name hypothesis failure

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3888]
Testrun: https://github.com/open-formulieren/open-forms/actions/runs/7912507989/job/21598378638

Output:

```
ERROR: test_names_do_not_break_pdf_saving_to_disk (openforms.submissions.tests.test_models.PDFSubmissionReportTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 852, in _execute_once_for_engine
    result = self.execute_once(data)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 791, in execute_once
    result = self.test_runner(data, run)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/executors.py", line 65, in <lambda>
    return lambda data, function: old_school(lambda: function(data))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/executors.py", line 24, in execute
    return function()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/executors.py", line 65, in <lambda>
    return lambda data, function: old_school(lambda: function(data))
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 787, in run
    return test(*args, **kwargs)
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/tests/test_models.py", line 637, in test_names_do_not_break_pdf_saving_to_disk
    @given(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 739, in test
    raise DeadlineExceeded(runtime, self.settings.deadline)
hypothesis.errors.DeadlineExceeded: Test took 818.32ms, which exceeds the deadline of 500.00ms

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/tests/test_models.py", line 637, in test_names_do_not_break_pdf_saving_to_disk
    @given(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 1387, in wrapped_test
    raise the_error_hypothesis_found
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hypothesis/core.py", line 816, in execute_once
    raise Flaky(
hypothesis.errors.Flaky: Hypothesis test_names_do_not_break_pdf_saving_to_disk(self=<openforms.submissions.tests.test_models.PDFSubmissionReportTests testMethod=test_names_do_not_break_pdf_saving_to_disk>, form_name='Þ🦹') produces unreliable results: Falsified on the first call but did not on a subsequent one
Falsifying example: test_names_do_not_break_pdf_saving_to_disk(
    self=<openforms.submissions.tests.test_models.PDFSubmissionReportTests testMethod=test_names_do_not_break_pdf_saving_to_disk>,
    form_name='Þ🦹',
)
Unreliable test timings! On an initial run, this test took 818.32ms, which exceeded the deadline of 500.00ms, but on a subsequent run it took 250.95 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

You can reproduce this example by temporarily adding @reproduce_failure('6.84.3', b'AAEA3QIBBwQBAfC4AA==') as a decorator on your test case
```

**Comment by sergei-maertens** [comment]
If this is because of the PDF file name -> let's just slugify the form name instead of using the real one.

However, this may also have to do with fonts and how things are processed for content *in* the PDF, then we need to figure out how much of a problem this really is and perhaps tweak the hypothesis deadlines.

**Comment by joeribekker** [comment]
Refinement: This is fixed
