### ISSUE TITLE
New flakiness in tests to be solved w/r to session locking

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3900]
```
ERROR: test_raising_loa_requirements_fails_in_flight_authentications (openforms.authentication.contrib.eherkenning.tests.test_signicat_integration.SignicatEHerkenningIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/unittest/mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "/home/runner/work/open-forms/open-forms/src/openforms/authentication/contrib/eherkenning/tests/test_signicat_integration.py", line 525, in test_raising_loa_requirements_fails_in_flight_authentications
    acs_response_2 = self.client.get(acs_url_2.url, follow=True)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 744, in get
    response = self._handle_redirects(response, data=data, **extra)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 850, in _handle_redirects
    response = request_method(path, data=data, content_type=content_type, follow=False, **extra)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 742, in get
    response = super().get(path, data=data, secure=secure, **extra)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 396, in get
    return self.generic('GET', path, secure=secure, **{
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 473, in generic
    return self.request(**r)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 719, in request
    self.check_exception(response)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/test/client.py", line 580, in check_exception
    raise exc_value
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/views.py", line 46, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/django/views/generic/base.py", line 189, in get
    url = self.get_redirect_url(*args, **kwargs)
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/views.py", line 167, in get_redirect_url
    add_submmission_to_session(submission, self.request.session)
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/utils.py", line 151, in add_submmission_to_session
    append_to_session_list(session, SUBMISSIONS_SESSION_KEY, str(submission.uuid))
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/utils.py", line 130, in append_to_session_list
    with _session_lock(session, session_key):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/runner/work/open-forms/open-forms/src/openforms/submissions/utils.py", line 81, in _session_lock
    with redis_cache.lock(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/redis/lock.py", line 168, in __exit__
    self.release()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/redis/lock.py", line 253, in release
    self.do_release(expected_token)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/redis/lock.py", line 259, in do_release
    raise LockNotOwnedError("Cannot release a lock that's no longer owned")
redis.exceptions.LockNotOwnedError: Cannot release a lock that's no longer owned
```

**Comment by sergei-maertens** [comment]
Duplicated by #3904 and tracking progress there
