### ISSUE TITLE
Crash on "validate date in the past"

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4172]
### Product versie / Product version

2.6.x / master / 652f572ac62472dfbd5e1ad7ed0dc1288b420046

### Omschrijf het probleem / Describe the bug

Traceback:

```
2024-04-15 16:45:07,249 ERROR django.request  Internal Server Error: /api/v2/submissions/5199bd05-63ff-4773-b59b-d56aa827560a/steps/31338729-7581-488c-919f-02fd7b2e6a1b/validate
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/utils/decorators.py", line 23, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/viewsets.py", line 584, in validate
    self._validate_step_input(request)
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/viewsets.py", line 596, in _validate_step_input
    serializer.is_valid(raise_exception=True)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/serializers.py", line 263, in validate_data
    self._run_formio_validation(data)
  File "/home/bbt/code/open-forms/src/openforms/submissions/api/serializers.py", line 288, in _run_formio_validation
    step_data_serializer = build_serializer(
  File "/home/bbt/code/open-forms/src/openforms/formio/service.py", line 105, in build_serializer
    return _build_serializer(components, register=_register or register, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/formio/serializers.py", line 152, in build_serializer
    field = register.build_serializer_field(component)
  File "/home/bbt/code/open-forms/src/openforms/formio/registry.py", line 215, in build_serializer_field
    return component_plugin.build_serializer_field(component)
  File "/home/bbt/code/open-forms/src/openforms/formio/components/custom.py", line 88, in build_serializer_field
    validators.append(MaxValueValidator(date.fromisoformat(max_date)))
ValueError: Invalid isoformat string: '2024-04-14T00:00:00+02:00'
```

### Stappen om te reproduceren / Steps to reproduce

1. Add a date field to the form
2. Go to the "validation" tab
3. Click "maximum date"
4. Select "In the past" as validation method
5. Leave "current date" unchecked
6. Save the component

I entered 01-01-1989 as date, and validation crashed with the error from the traceback

### Verwacht gedrag / Expected behavior

No crash and data validates

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Tasks:

- [x] Fix backend crash
- [ ] Port frontend bugfix for timezone offset with date parsing
