### ISSUE TITLE
Broken data migration crashes

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4247]
On our test env, from the logs:

```
Traceback (most recent call last):
  File "/app/src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/app/src/openforms/forms/migrations/0098_fix_forms_conditionals.py", line 19, in fix_forms_simple_conditionals
    config_modified = convert_simple_conditionals(definition.configuration)
  File "/app/src/openforms/formio/migration_converters.py", line 191, in convert_simple_conditionals
    comparison_component = config[comparison_component_key]
  File "/app/src/openforms/formio/datastructures.py", line 52, in __getitem__
    return self.component_map[key]
KeyError: 'ingeschrevenOnderneming.rechtsvorm'
  Applying forms.0098_fix_forms_conditionals...
```

Not sure what exactly is going on :)

**Comment by sergei-maertens** [comment]
Some more info from Sentry:

![image](https://github.com/open-formulieren/open-forms/assets/5518550/520cfcf8-d726-4628-87a4-a5e64f937f49)

I'm suspecting some weird key-translation thing with `editgrid` :thinking: 

It crashes on `<FormDefinition: FormDefinition object (1891)>` so we should be able to reproduce easily.
