### ISSUE TITLE
Onduidelijke foutmelding na toevoegen nieuwe ZGW API's Registratiepluginoptie bij formulier

### ISSUE THREAD

**Issue by andyverberne** [open-formulieren/open-forms#4639]
### Product versie / Product version

2.7.6

### Customer reference

Dimpact

### Omschrijf het probleem / Describe the bug

Na het drukken op de Opslaan knop bij het toevoegen van een Registratieplugin optie verschijnt de volgende foutmelding waarbij onduidelijk is waar de fout nu precies zit.

![image](https://github.com/user-attachments/assets/9bd78753-b547-461c-ad41-6d4d71b74714)

Na analyse van de volgende stacktrace in Open Formulieren:

```python
`2024-09-08 07:52:07,781 ERROR django.request  Internal Server Error: /api/v2/forms/55d393f3-a8aa-4c2a-82e9-e23de3d1cc2e
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/src/./openforms/utils/decorators.py", line 23, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/drf_spectacular/drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 634, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 693, in to_internal_value
    validated = self.run_child_validation(item)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 653, in run_child_validation
    return self.child.run_validation(data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "/app/src/./openforms/forms/api/serializers/form.py", line 91, in validate
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "/app/src/./openforms/registrations/contrib/zgw_apis/options.py", line 151, in validate
    zaaktype_exists = any(
  File "/app/src/./openforms/registrations/contrib/zgw_apis/options.py", line 152, in <genexpr>
    zaaktype_url in catalogus["zaaktypen"] for catalogus in catalogi
KeyError: 'zaaktypen'
```
En omdat e-Suite onderstaande request ontvangt van Open Formulieren:
```python
{
    "resource": "https://dmidoffice2.esuite-development.net/zgw-apis-provider/ztc/api/v1/catalogussen",
    "query": null,
    "body": null
}
```

Waarop e-Suite het volgende antwoord:

```python
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "url": "https://dmidoffice2.esuite-development.net/zgw-apis-provider/ztc/api/v1/catalogussen/984b4d18-4fd2-4274-b62a-672d3805a138",
            "domein": "ALLE",
            "rsin": null,
            "contactpersoonBeheerNaam": null
        }
    ]
}
```

Is de conclussie dat het om het veld **Zaaktype** gaat.

### Stappen om te reproduceren / Steps to reproduce

Maak een ZGW API's Registratieplugin optie aan en zorg dat het opvragen van de catalogus REST call een response geeft zonder zaaktypen

### Verwacht gedrag / Expected behavior

Een duidelijke melding dat er een probleem is met het valideren van het zaaktype

### Screen resolution

None

### Device

None

### OS

None

**Comment by andyverberne** [comment]
Zie ook: #4640

**Comment by joeribekker** [comment]
Refinement: The root cause is #4640 and we can't define error-handling for server responses that do not adhere to the API specification.
