### ISSUE TITLE
Forms cannot be submitted due to an error in the form summary template tag?

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#559]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/app/src/./openforms/submissions/api/viewsets.py", line 157, in _complete
    "confirmation_page_content": submission.render_confirmation_page(),
  File "/app/src/./openforms/submissions/models.py", line 188, in render_confirmation_page
    rendered_content = Template(template).render(Context(self.data))
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/app/src/./openforms/emails/templatetags/form_summary.py", line 12, in summary
    return filter_data_to_show_in_email(context.flatten())
  File "/app/src/./openforms/emails/templatetags/form_summary.py", line 21, in filter_data_to_show_in_email
    form = context["_form"]
KeyError: '_form'
```

**Comment by shea-maykinmedia** [comment]
The reason for this bug is that the form had `{% summary %}` in the `Submission confirmation template`/`Bevestigingspagina tekst` field of the `Form`.  

When this line of code https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/models.py#L197 then it was trying to load the `summary` template tag specified here https://github.com/open-formulieren/open-forms/blob/master/src/openforms/emails/templatetags/form_summary.py#L12 which eventually called this line https://github.com/open-formulieren/open-forms/blob/master/src/openforms/emails/templatetags/form_summary.py#L21 and then the exception was thrown because there was no `_form` attribute in the context.

One potential option would be to modify https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/models.py#L197 to something like
```python
context = {
  "_form": self.form,
  **self.data
}
rendered_content = Template(template).render(Context(context))
```
however the `summary` template tag was built to be used for emails so we would want to double check it functions properly when using it to display HTML pages.

**Comment by sergei-maertens** [comment]
Having styling related to both browsers and e-mail clients is not recommended, since e-mail clients are absolutely horrendous. I'd advise not using the `{% summary %}` tag in the confirmation page.

**Comment by joeribekker** [comment]
I agree but I'll refine this bug so that the error can then not be made anymore by only allowing certain tags, as a future enhancement.
