### ISSUE TITLE
Can't save the General Configuration without a municipality logo

### ISSUE THREAD

**Issue by shea-maykinmedia** [open-formulieren/open-forms#581]
The `Municipality logo` in the `General Configuration` admin is not a required field but if one is added then an exception will be thrown.

The issue is that when you save code is run to get the extension https://github.com/open-formulieren/open-forms/blob/master/src/openforms/utils/form_fields.py#L39 but since `data` will be `None` the exception shown below is thrown.

**Stacktrace**

```python
2021-08-20 14:32:14,713 ERROR django.request  Internal Server Error: /admin/config/globalconfiguration/
Traceback (most recent call last):
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/solo/admin.py", line 64, in change_view
    return super(SingletonModelAdmin, self).change_view(
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1648, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1529, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    form_validated = form.is_valid()
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/forms/forms.py", line 397, in _clean_fields
    value = field.clean(value, initial)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/forms/fields.py", line 585, in clean
    return super().clean(data)
  File "/Users/shea/Projects/open-forms/env/lib/python3.8/site-packages/django/forms/fields.py", line 148, in clean
    value = self.to_python(value)
  File "/Users/shea/Projects/open-forms/src/openforms/utils/form_fields.py", line 39, in to_python
    extension = get_extension(data)
  File "/Users/shea/Projects/open-forms/src/openforms/utils/form_fields.py", line 15, in get_extension
    return Path(file_like.name).suffix[1:].lower()
AttributeError: 'NoneType' object has no attribute 'name'
2021-08-20 14:32:14,990 ERROR django.server  "POST /admin/config/globalconfiguration/ HTTP/1.1" 500 189222
```

**Comment by shea-maykinmedia** [comment]
Just above where we get the extension I added the code

```python
        if not data:
            return super().to_python(data)
```

and this seemed to fix the problem so doing something like this should fix the issue but I'll leave it to @joeribekker for now to assign and prioritize this.
